### ISSUE TITLE
Make sure users rename the application name in package.json

### ISSUE THREAD

**Issue by KINKCreative** [ghiscoding/Realtime-TODO-Aurelia-Auth-RethinkDB#2]
The package name is set to node-rethinkdb and it errors out on Node v6.2.0 - can't install node-rethinkdb as a dependency of itself and npm won't start the server. Renaming the app there allows the module to install.

**Comment by ghiscoding** [comment]
Yeah right, I took the template from somewhere and forgot to rename it. Anyway, it's fixed now, thanks for letting me know
