### ISSUE TITLE
Client-WP unable to lauch, 

### ISSUE THREAD

**Issue by antfry** [ghiscoding/Realtime-TODO-Aurelia-Auth-RethinkDB#4]
Having some issues with client-wp getting it working with npm. Log isn't very descriptive, server is working with no issues.

npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v4.0.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v4.0.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start:client-only' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose run-script [ 'prestart:client-only',
4 verbose run-script   'start:client-only',
4 verbose run-script   'poststart:client-only' ]
5 info prestart:client-only Aurelia-Auth-TODO-RethinkDB@1.1.0
6 info start:client-only Aurelia-Auth-TODO-RethinkDB@1.1.0
7 verbose unsafe-perm in lifecycle true
8 info Aurelia-Auth-TODO-RethinkDB@1.1.0 Failed to exec start:client-only script
9 verbose stack Error: Aurelia-Auth-TODO-RethinkDB@1.1.0 start:client-only: `npm run server:dev`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v4.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v4.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid Aurelia-Auth-TODO-RethinkDB@1.1.0
11 verbose cwd /root/Realtime-TODO-Aurelia-Auth-RethinkDB/client-wp
12 error Linux 4.2.0-42-generic
13 error argv "/root/.nvm/versions/node/v4.0.0/bin/node" "/root/.nvm/versions/node/v4.0.0/bin/npm" "run" "start:client-only"
14 error node v4.0.0
15 error npm  v2.14.2
16 error code ELIFECYCLE
17 error Aurelia-Auth-TODO-RethinkDB@1.1.0 start:client-only: `npm run server:dev`
17 error Exit status 1
18 error Failed at the Aurelia-Auth-TODO-RethinkDB@1.1.0 start:client-only script 'npm run server:dev'.
18 error This is most likely a problem with the Aurelia-Auth-TODO-RethinkDB package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run server:dev
18 error You can get their info via:
18 error     npm owner ls Aurelia-Auth-TODO-RethinkDB
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by ghiscoding** [comment]
possibly because of some updates to some of the packages. I haven't tried in a while, will eventually update it to the latest webpack by Jods, just didn't have time. You can try to fix the versions, try removing all the caret in front of all the dependencies "^". Not exactly ideal but you'll have more chances that it works.

**Comment by antfry** [comment]
Thank you for the quick response, I solved the issue by updating node.

**Comment by ghiscoding** [comment]
Oh cool, thanks for the feedback :) 

Not sure if you know already, but I also create a few [Aurelia Bootstrap Plugins](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins), you might want to take a look. 

Cheers
